### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by certik** [fortran-lang/registry#61]
* [ ] Frontend for reporting and generating malicious reports (backend is already done)
* [ ] Ratings and stars
* [ ] Downloading of packages using `fpm` from the registry
* [ ] Dependency resolution for downloading the package
